IMPORTING IMPORTANT DATASCIENCE LIBRARIES

In [94]:


import numpy as np
import pandas as pd
import matplotlib.pyplot

IMPORTING THE DATASET FROM THE DESKTOP AND READ IT INTO THE IDLE

In [99]:
dataset = pd.read_csv('Dataset.csv')  

dataset.head(5)

Developer   Age   Salary Married
0   Karachi  42.0  78000.0      No
1    Lahore  32.0  48000.0     Yes
2   Karachi  36.0  60000.0      No
3    Multan  41.0  68000.0      No
4    Lahore  42.0      NaN     Yes

DIVISON OF DATASET INTO FEATURES AND LABELS 

In [47]:
X = dataset.iloc[: , :-1].values
XY = dataset.iloc[: , :-1].values
XYZ = dataset.iloc[: , :-1].values
Y = dataset['Married'].values
X

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, nan],
       ['Multan', 43.0, 59000.0],
       ['Karachi', nan, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

HANDLING THE MISSING VALUES BY USING MEAN AND SKLEARN LIBRARY

In [50]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='mean' , axis =0)
imputer=imputer.fit(X[: , 1:3])
X[: , 1:3] = imputer.transform(X[: ,1:3])
X

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, 68777.77777777778],
       ['Multan', 43.0, 59000.0],
       ['Karachi', 40.44444444444444, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

HANDLING THE MISSING VALUES BY USING MEDIAN AND SKLEARN LIBRARY

In [101]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='median' , axis =0)
imputer=imputer.fit(XY[: , 1:3])
XY[: , 1:3] = imputer.transform(XY[: ,1:3])
XY

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, 68000.0],
       ['Multan', 43.0, 59000.0],
       ['Karachi', 42.0, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

HANDLING THE MISSING VALUES BY USING MOST FREQUENT VALUE FROM THE DATASET AND SKLEARN LIBRARY

In [51]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='most_frequent' , axis =0)
imputer=imputer.fit(XYZ[: , 1:3])
XYZ[: , 1:3] = imputer.transform(XYZ[: ,1:3])
XYZ

array([['Karachi', 42.0, 78000.0],
       ['Lahore', 32.0, 48000.0],
       ['Karachi', 36.0, 60000.0],
       ['Multan', 41.0, 68000.0],
       ['Lahore', 42.0, 59000.0],
       ['Multan', 43.0, 59000.0],
       ['Karachi', 32.0, 59000.0],
       ['Lahore', 44.0, 79000.0],
       ['Multan', 52.0, 99000.0],
       ['Lahore', 32.0, 69000.0]], dtype=object)

HANDLING THE MISSING VALUE BY REMOVING THE NAN VALUES ROWS FROM THE DATASET

In [52]:
dataset.dropna(axis = 0)

Developer   Age   Salary Married
0   Karachi  42.0  78000.0      No
1    Lahore  32.0  48000.0     Yes
2   Karachi  36.0  60000.0      No
3    Multan  41.0  68000.0      No
5    Multan  43.0  59000.0     Yes
7    Lahore  44.0  79000.0     Yes
8    Multan  52.0  99000.0      No
9    Lahore  32.0  69000.0     Yes

WHEN THE FEATURES ARE IN THE FORM OF CATEGORY OR CLASS THEN WE USE LABEL ENCODER AS BELOW FORM

In [61]:
from sklearn.preprocessing import LabelEncoder
labalencoder_X = LabelEncoder()
X[:,0] = labalencoder_X.fit_transform(X[:,0])
X


array([[0, 42.0, 78000.0],
       [1, 32.0, 48000.0],
       [0, 36.0, 60000.0],
       [2, 41.0, 68000.0],
       [1, 42.0, 68777.77777777778],
       [2, 43.0, 59000.0],
       [0, 40.44444444444444, 59000.0],
       [1, 44.0, 79000.0],
       [2, 52.0, 99000.0],
       [1, 32.0, 69000.0]], dtype=object)

ONEHOT ENCODER IS USED TO GIVE THE CATEGORICAL VALUE IN THE FEATURES AND IT HELPS TO GIVE 
DISTINGUISH THE FEATUTRES OF CATEGORICAL FORM

In [71]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
X


array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.20000000e+01,   7.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   3.20000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   3.60000000e+01,   6.00000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   4.10000000e+01,   6.80000000e+04],
    

TRAIN TEST SPLIT IS USED TO DIVIDE THE DATASET INTO TRAINING AND TESTING PART IN SUPERVISED LEARNING 
AFTERWHICH WE APPLY DIFFERENT ALGO IN IT.

from sklearn.cross_validation import train_test_split
train_x , test_x , train_y , test_y = train_test_split(X,Y ,test_size = 0.2 ,random_state =0)

STANDARDSCALER IS USED TO GIVE THE CLOSE VALUE OF AALL THE FEATURES AND LABELS BETWEEN -1 AND 1
IT HELPS TO STANDARDIZE THE DATA AND GIVE GOOD PREDICTIONS.

In [92]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
test_x = sc_X.fit_transform(test_x)
train_x = sc_X.fit_transform(train_x)
test_x
train_x

array([[ 0.57735027, -0.57735027,  0.57735027, -0.57735027,  0.57735027,
        -0.57735027,  0.57735027, -0.57735027,  1.        , -0.57735027,
         0.54554305,  0.2758114 ],
       [ 0.57735027, -0.57735027,  0.57735027, -0.57735027,  0.57735027,
        -0.57735027,  0.57735027, -0.57735027,  1.        , -0.57735027,
        -1.68622397,  0.29867659],
       [ 0.57735027, -0.57735027,  0.57735027, -0.57735027,  0.57735027,
        -0.57735027,  0.57735027, -0.57735027,  1.        , -0.57735027,
        -1.68622397, -1.86208422],
       [-1.73205081,  1.73205081, -1.73205081,  1.73205081, -1.73205081,
         1.73205081, -1.73205081,  1.73205081, -1.        , -0.57735027,
         0.19837929, -0.73025713],
       [ 0.57735027, -0.57735027,  0.57735027, -0.57735027,  0.57735027,
        -0.57735027,  0.57735027, -0.57735027,  1.        , -0.57735027,
         0.99189645,  1.32761031],
       [ 0.57735027, -0.57735027,  0.57735027, -0.57735027,  0.57735027,
        -0.57735027,  