In [61]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [62]:
#Import the data set from Desktop
data =pd.read_csv('M_Regression.csv')
data.head(5)

indoor    outdoor   domestic     Profit
0  165349.20  136897.80  471784.10  192261.83
1  162597.70  151377.59  443898.53  191792.06
2  153441.51  101145.55  407934.54  191050.39
3  144372.41  118671.85  383199.62  182901.99
4  142107.34   91391.77  366168.42  166187.94

In [63]:
#Checking of Null values
data.isnull().sum()

indoor      0
outdoor     0
domestic    0
Profit      0
dtype: int64

In [64]:
#Info of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
indoor      50 non-null float64
outdoor     50 non-null float64
domestic    50 non-null float64
Profit      50 non-null float64
dtypes: float64(4)
memory usage: 1.6 KB


In [65]:
#Description of Dataset
data.describe()

indoor        outdoor       domestic         Profit
count      50.000000      50.000000      50.000000      50.000000
mean    73721.615600  121344.639600  211025.097800  112012.639200
std     45902.256482   28017.802755  122290.310726   40306.180338
min         0.000000   51283.140000       0.000000   14681.400000
25%     39936.370000  103730.875000  129300.132500   90138.902500
50%     73051.080000  122699.795000  212716.240000  107978.190000
75%    101602.800000  144842.180000  299469.085000  139765.977500
max    165349.200000  182645.560000  471784.100000  192261.830000

In [66]:
#Features Extraction from the dataset
X= data.drop(['Profit'],axis=1)
X.head(5)

indoor    outdoor   domestic
0  165349.20  136897.80  471784.10
1  162597.70  151377.59  443898.53
2  153441.51  101145.55  407934.54
3  144372.41  118671.85  383199.62
4  142107.34   91391.77  366168.42

In [67]:
#Label Extraction From the dataset
Y = data.iloc[:,3:4].values
Y

array([[ 192261.83],
       [ 191792.06],
       [ 191050.39],
       [ 182901.99],
       [ 166187.94],
       [ 156991.12],
       [ 156122.51],
       [ 155752.6 ],
       [ 152211.77],
       [ 149759.96],
       [ 146121.95],
       [ 144259.4 ],
       [ 141585.52],
       [ 134307.35],
       [ 132602.65],
       [ 129917.04],
       [ 126992.93],
       [ 125370.37],
       [ 124266.9 ],
       [ 122776.86],
       [ 118474.03],
       [ 111313.02],
       [ 110352.25],
       [ 108733.99],
       [ 108552.04],
       [ 107404.34],
       [ 105733.54],
       [ 105008.31],
       [ 103282.38],
       [ 101004.64],
       [  99937.59],
       [  97483.56],
       [  97427.84],
       [  96778.92],
       [  96712.8 ],
       [  96479.51],
       [  90708.19],
       [  89949.14],
       [  81229.06],
       [  81005.76],
       [  78239.91],
       [  77798.83],
       [  71498.49],
       [  69758.98],
       [  65200.33],
       [  64926.08],
       [  49490.75],
       [  425

In [68]:
#Training and Testing Data (divide the data into two part) for appllying the algorithim
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(X,Y,test_size=0.3 , random_state=0)

In [69]:
#Building a Regression Model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [70]:
#for predict the test values
y_prediction = model.predict(test_x)
y_prediction

array([[ 104054.44293869],
       [ 132719.3459701 ],
       [ 133640.26830949],
       [  72294.76911458],
       [ 179685.62227843],
       [ 114508.97572031],
       [  66305.23069863],
       [  98297.69326565],
       [ 114277.91894933],
       [ 169112.36095691],
       [  96257.40152149],
       [  87916.97242208],
       [ 110687.33942598],
       [  90670.8337806 ],
       [ 127780.63539583]])

In [71]:
#Accuracy
model.score(test_x,test_y)

0.93551883371182165

In [72]:
#Comparison between Testing and Predicting values
print(test_y,end='')
print('\n',y_prediction ,'\n',  end='')

[[ 103282.38]
 [ 144259.4 ]
 [ 146121.95]
 [  77798.83]
 [ 191050.39]
 [ 105008.31]
 [  81229.06]
 [  97483.56]
 [ 110352.25]
 [ 166187.94]
 [  96778.92]
 [  96479.51]
 [ 105733.54]
 [  96712.8 ]
 [ 124266.9 ]]
 [[ 104054.44293869]
 [ 132719.3459701 ]
 [ 133640.26830949]
 [  72294.76911458]
 [ 179685.62227843]
 [ 114508.97572031]
 [  66305.23069863]
 [  98297.69326565]
 [ 114277.91894933]
 [ 169112.36095691]
 [  96257.40152149]
 [  87916.97242208]
 [ 110687.33942598]
 [  90670.8337806 ]
 [ 127780.63539583]] 
